# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_designer\CurrentPress.ui'
#
# Created: Mon Nov 04 18:01:42 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_CurrentPress(object):
    def setupUi(self, CurrentPress):
        CurrentPress.setObjectName("CurrentPress")
        CurrentPress.resize(747, 302)
        CurrentPress.setWindowTitle("")
        CurrentPress.setStyleSheet("QLabel{\n"
"background-color:#bebebe; \n"
"border-radius: 8px;   \n"
"padding: 5px; \n"
"}")
        self.horizontalLayout = QtGui.QHBoxLayout(CurrentPress)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(9)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(CurrentPress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(30, 90))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.press_lcd1 = QtGui.QLCDNumber(CurrentPress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.press_lcd1.sizePolicy().hasHeightForWidth())
        self.press_lcd1.setSizePolicy(sizePolicy)
        self.press_lcd1.setNumDigits(6)
        self.press_lcd1.setObjectName("press_lcd1")
        self.gridLayout.addWidget(self.press_lcd1, 0, 1, 1, 1)
        self.press_lcd2 = QtGui.QLCDNumber(CurrentPress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.press_lcd2.sizePolicy().hasHeightForWidth())
        self.press_lcd2.setSizePolicy(sizePolicy)
        self.press_lcd2.setNumDigits(6)
        self.press_lcd2.setProperty("value", 0.0)
        self.press_lcd2.setObjectName("press_lcd2")
        self.gridLayout.addWidget(self.press_lcd2, 0, 3, 1, 1)
        self.label_2 = QtGui.QLabel(CurrentPress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(30, 90))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.press_lcd3 = QtGui.QLCDNumber(CurrentPress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.press_lcd3.sizePolicy().hasHeightForWidth())
        self.press_lcd3.setSizePolicy(sizePolicy)
        self.press_lcd3.setNumDigits(6)
        self.press_lcd3.setObjectName("press_lcd3")
        self.gridLayout.addWidget(self.press_lcd3, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(CurrentPress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setMaximumSize(QtCore.QSize(30, 90))
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.press_lcd4 = QtGui.QLCDNumber(CurrentPress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.press_lcd4.sizePolicy().hasHeightForWidth())
        self.press_lcd4.setSizePolicy(sizePolicy)
        self.press_lcd4.setNumDigits(6)
        self.press_lcd4.setProperty("value", 0.0)
        self.press_lcd4.setObjectName("press_lcd4")
        self.gridLayout.addWidget(self.press_lcd4, 1, 3, 1, 1)
        self.label_3 = QtGui.QLabel(CurrentPress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setMaximumSize(QtCore.QSize(30, 90))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.press_lcd5 = QtGui.QLCDNumber(CurrentPress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.press_lcd5.sizePolicy().hasHeightForWidth())
        self.press_lcd5.setSizePolicy(sizePolicy)
        self.press_lcd5.setNumDigits(6)
        self.press_lcd5.setObjectName("press_lcd5")
        self.gridLayout.addWidget(self.press_lcd5, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(CurrentPress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setMaximumSize(QtCore.QSize(30, 90))
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1)
        self.press_lcd6 = QtGui.QLCDNumber(CurrentPress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.press_lcd6.sizePolicy().hasHeightForWidth())
        self.press_lcd6.setSizePolicy(sizePolicy)
        self.press_lcd6.setNumDigits(6)
        self.press_lcd6.setObjectName("press_lcd6")
        self.gridLayout.addWidget(self.press_lcd6, 2, 3, 1, 1)
        self.label_4 = QtGui.QLabel(CurrentPress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setMaximumSize(QtCore.QSize(30, 90))
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ready_button = QtGui.QPushButton(CurrentPress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ready_button.sizePolicy().hasHeightForWidth())
        self.ready_button.setSizePolicy(sizePolicy)
        self.ready_button.setMinimumSize(QtCore.QSize(120, 120))
        self.ready_button.setMaximumSize(QtCore.QSize(120, 120))
        self.ready_button.setCursor(QtCore.Qt.PointingHandCursor)
        self.ready_button.setStyleSheet("QPushButton#ready_button {\n"
"    font: 20pt Arial;\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0.05                     #77d42a, stop:1 #5cb811);\n"
"    border-style:outset;\n"
"    border-width:6px;\n"
"    border-radius:60px;\n"
"    border-color:#636363;\n"
"    padding:4px 8px;}\n"
"QPushButton#ready_button:hover{\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0.05                     #5cb811, stop:1 #77d42a);}\n"
"QPushButton#ready_button:pressed{\n"
"     background: #adff2f;\n"
"     border-style: inset;}")
        self.ready_button.setIconSize(QtCore.QSize(40, 40))
        self.ready_button.setObjectName("ready_button")
        self.verticalLayout.addWidget(self.ready_button)
        self.label_ready = QtGui.QLabel(CurrentPress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ready.sizePolicy().hasHeightForWidth())
        self.label_ready.setSizePolicy(sizePolicy)
        self.label_ready.setMinimumSize(QtCore.QSize(120, 0))
        self.label_ready.setStyleSheet("background-color:rgba(0,0,0,0); \n"
"border-radius: 0px;   \n"
"padding: 5px; ")
        self.label_ready.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_ready.setObjectName("label_ready")
        self.verticalLayout.addWidget(self.label_ready)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(CurrentPress)
        QtCore.QMetaObject.connectSlotsByName(CurrentPress)

    def retranslateUi(self, CurrentPress):
        self.label.setText(QtGui.QApplication.translate("CurrentPress", "<html><head/><body><li><span style=\" font-size:12pt; color:#0000ff;\">通</span></li><li><span style=\" font-size:12pt; color:#0000ff;\">道</span></li><li><span style=\" font-size:12pt; color:#0000ff;\">1</span></li></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CurrentPress", "<html><head/><body><li><span style=\" font-size:12pt; color:#0000ff;\">通</span></li><li><span style=\" font-size:12pt; color:#0000ff;\">道</span></li><li><span style=\" font-size:12pt; color:#0000ff;\">3</span></li></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("CurrentPress", "<html><head/><body><li><span style=\" font-size:12pt; color:#0000ff;\">通</span></li><li><span style=\" font-size:12pt; color:#0000ff;\">道</span></li><li><span style=\" font-size:12pt; color:#0000ff;\">4</span></li></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("CurrentPress", "<html><head/><body><li><span style=\" font-size:12pt; color:#0000ff;\">通</span></li><li><span style=\" font-size:12pt; color:#0000ff;\">道</span></li><li><span style=\" font-size:12pt; color:#0000ff;\">5</span></li></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("CurrentPress", "<html><head/><body><li><span style=\" font-size:12pt; color:#0000ff;\">通</span></li><li><span style=\" font-size:12pt; color:#0000ff;\">道</span></li><li><span style=\" font-size:12pt; color:#0000ff;\">6</span></li></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("CurrentPress", "<html><head/><body><li><span style=\" font-size:12pt; color:#0000ff;\">通</span></li><li><span style=\" font-size:12pt; color:#0000ff;\">道</span></li><li><span style=\" font-size:12pt; color:#0000ff;\">2</span></li></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.ready_button.setText(QtGui.QApplication.translate("CurrentPress", "准备", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ready.setText(QtGui.QApplication.translate("CurrentPress", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">准备测试</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

import Icons_rc
