# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_designer\CalibrationDialog.ui'
#
# Created: Wed Nov 27 14:45:53 2013
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_CalibrationDialog(object):
    def setupUi(self, CalibrationDialog):
        CalibrationDialog.setObjectName("CalibrationDialog")
        CalibrationDialog.resize(210, 320)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CalibrationDialog.sizePolicy().hasHeightForWidth())
        CalibrationDialog.setSizePolicy(sizePolicy)
        CalibrationDialog.setMinimumSize(QtCore.QSize(210, 320))
        CalibrationDialog.setMaximumSize(QtCore.QSize(210, 320))
        self.verticalLayout = QtGui.QVBoxLayout(CalibrationDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(CalibrationDialog)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.press_spin1 = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.press_spin1.sizePolicy().hasHeightForWidth())
        self.press_spin1.setSizePolicy(sizePolicy)
        self.press_spin1.setWrapping(False)
        self.press_spin1.setFrame(True)
        self.press_spin1.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.press_spin1.setPrefix("")
        self.press_spin1.setDecimals(4)
        self.press_spin1.setMinimum(-30.0)
        self.press_spin1.setMaximum(30.0)
        self.press_spin1.setSingleStep(0.001)
        self.press_spin1.setProperty("value", -0.1013)
        self.press_spin1.setObjectName("press_spin1")
        self.horizontalLayout.addWidget(self.press_spin1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(CalibrationDialog)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setSpacing(30)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.press_spin2 = QtGui.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.press_spin2.sizePolicy().hasHeightForWidth())
        self.press_spin2.setSizePolicy(sizePolicy)
        self.press_spin2.setDecimals(4)
        self.press_spin2.setMinimum(-30.0)
        self.press_spin2.setMaximum(30.0)
        self.press_spin2.setSingleStep(0.001)
        self.press_spin2.setProperty("value", -0.1013)
        self.press_spin2.setObjectName("press_spin2")
        self.horizontalLayout_2.addWidget(self.press_spin2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(CalibrationDialog)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setSpacing(30)
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.press_spin3 = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.press_spin3.sizePolicy().hasHeightForWidth())
        self.press_spin3.setSizePolicy(sizePolicy)
        self.press_spin3.setDecimals(4)
        self.press_spin3.setMinimum(-30.0)
        self.press_spin3.setMaximum(30.0)
        self.press_spin3.setSingleStep(0.001)
        self.press_spin3.setProperty("value", -0.1013)
        self.press_spin3.setObjectName("press_spin3")
        self.horizontalLayout_3.addWidget(self.press_spin3)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(CalibrationDialog)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setSpacing(30)
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.press_spin4 = QtGui.QDoubleSpinBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.press_spin4.sizePolicy().hasHeightForWidth())
        self.press_spin4.setSizePolicy(sizePolicy)
        self.press_spin4.setDecimals(4)
        self.press_spin4.setMinimum(-30.0)
        self.press_spin4.setMaximum(30.0)
        self.press_spin4.setSingleStep(0.001)
        self.press_spin4.setProperty("value", -0.1013)
        self.press_spin4.setObjectName("press_spin4")
        self.horizontalLayout_4.addWidget(self.press_spin4)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(CalibrationDialog)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setSpacing(30)
        self.horizontalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtGui.QLabel(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.press_spin5 = QtGui.QDoubleSpinBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.press_spin5.sizePolicy().hasHeightForWidth())
        self.press_spin5.setSizePolicy(sizePolicy)
        self.press_spin5.setDecimals(4)
        self.press_spin5.setMinimum(-30.0)
        self.press_spin5.setMaximum(30.0)
        self.press_spin5.setSingleStep(0.001)
        self.press_spin5.setProperty("value", -0.1013)
        self.press_spin5.setObjectName("press_spin5")
        self.horizontalLayout_5.addWidget(self.press_spin5)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(CalibrationDialog)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_6.setSpacing(30)
        self.horizontalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.press_spin6 = QtGui.QDoubleSpinBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.press_spin6.sizePolicy().hasHeightForWidth())
        self.press_spin6.setSizePolicy(sizePolicy)
        self.press_spin6.setDecimals(4)
        self.press_spin6.setMinimum(-30.0)
        self.press_spin6.setMaximum(30.0)
        self.press_spin6.setSingleStep(0.001)
        self.press_spin6.setProperty("value", -0.1013)
        self.press_spin6.setObjectName("press_spin6")
        self.horizontalLayout_6.addWidget(self.press_spin6)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cancel_button = QtGui.QPushButton(CalibrationDialog)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_7.addWidget(self.cancel_button)
        self.ok_button = QtGui.QPushButton(CalibrationDialog)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout_7.addWidget(self.ok_button)
        self.verticalLayout.addLayout(self.horizontalLayout_7)

        self.retranslateUi(CalibrationDialog)
        QtCore.QObject.connect(self.cancel_button, QtCore.SIGNAL("clicked()"), CalibrationDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CalibrationDialog)

    def retranslateUi(self, CalibrationDialog):
        CalibrationDialog.setWindowTitle(QtGui.QApplication.translate("CalibrationDialog", "压力校准", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CalibrationDialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">通 道  1</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.press_spin1.setSuffix(QtGui.QApplication.translate("CalibrationDialog", "Mpa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CalibrationDialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">通 道  2</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.press_spin2.setSuffix(QtGui.QApplication.translate("CalibrationDialog", "Mpa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("CalibrationDialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">通 道  3</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.press_spin3.setSuffix(QtGui.QApplication.translate("CalibrationDialog", "Mpa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("CalibrationDialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">通 道  4</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.press_spin4.setSuffix(QtGui.QApplication.translate("CalibrationDialog", "Mpa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("CalibrationDialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">通 道 5</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.press_spin5.setSuffix(QtGui.QApplication.translate("CalibrationDialog", "Mpa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("CalibrationDialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">通 道  6</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.press_spin6.setSuffix(QtGui.QApplication.translate("CalibrationDialog", "Mpa", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_button.setText(QtGui.QApplication.translate("CalibrationDialog", "取消", None, QtGui.QApplication.UnicodeUTF8))
        self.ok_button.setText(QtGui.QApplication.translate("CalibrationDialog", "确定", None, QtGui.QApplication.UnicodeUTF8))

