# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_designer\ConfigDialog.ui'
#
# Created: Fri Nov 01 11:10:30 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ConfigDialog(object):
    def setupUi(self, ConfigDialog):
        ConfigDialog.setObjectName("ConfigDialog")
        ConfigDialog.resize(577, 475)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ConfigDialog.sizePolicy().hasHeightForWidth())
        ConfigDialog.setSizePolicy(sizePolicy)
        ConfigDialog.setMinimumSize(QtCore.QSize(0, 0))
        ConfigDialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ConfigDialog.setWindowIcon(icon)
        ConfigDialog.setStyleSheet("QLabel{\n"
"font-size: 10.5pt;\n"
"}\n"
"QGroupBox::groupBox_2{\n"
"font:15pt;\n"
"}")
        ConfigDialog.setModal(True)
        self.verticalLayout_5 = QtGui.QVBoxLayout(ConfigDialog)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtGui.QGroupBox(ConfigDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.num_chk4 = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_chk4.sizePolicy().hasHeightForWidth())
        self.num_chk4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.num_chk4.setFont(font)
        self.num_chk4.setObjectName("num_chk4")
        self.gridLayout.addWidget(self.num_chk4, 3, 1, 1, 1)
        self.num_edit4 = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_edit4.sizePolicy().hasHeightForWidth())
        self.num_edit4.setSizePolicy(sizePolicy)
        self.num_edit4.setMaxLength(10)
        self.num_edit4.setAlignment(QtCore.Qt.AlignCenter)
        self.num_edit4.setObjectName("num_edit4")
        self.gridLayout.addWidget(self.num_edit4, 3, 0, 1, 1)
        self.num_chk3 = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_chk3.sizePolicy().hasHeightForWidth())
        self.num_chk3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.num_chk3.setFont(font)
        self.num_chk3.setObjectName("num_chk3")
        self.gridLayout.addWidget(self.num_chk3, 2, 1, 1, 1)
        self.num_edit3 = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_edit3.sizePolicy().hasHeightForWidth())
        self.num_edit3.setSizePolicy(sizePolicy)
        self.num_edit3.setMaxLength(10)
        self.num_edit3.setAlignment(QtCore.Qt.AlignCenter)
        self.num_edit3.setObjectName("num_edit3")
        self.gridLayout.addWidget(self.num_edit3, 2, 0, 1, 1)
        self.num_edit1 = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_edit1.sizePolicy().hasHeightForWidth())
        self.num_edit1.setSizePolicy(sizePolicy)
        self.num_edit1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.num_edit1.setText("")
        self.num_edit1.setMaxLength(10)
        self.num_edit1.setFrame(True)
        self.num_edit1.setCursorPosition(0)
        self.num_edit1.setAlignment(QtCore.Qt.AlignCenter)
        self.num_edit1.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.num_edit1.setObjectName("num_edit1")
        self.gridLayout.addWidget(self.num_edit1, 0, 0, 1, 1)
        self.num_chk1 = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_chk1.sizePolicy().hasHeightForWidth())
        self.num_chk1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.num_chk1.setFont(font)
        self.num_chk1.setObjectName("num_chk1")
        self.gridLayout.addWidget(self.num_chk1, 0, 1, 1, 1)
        self.num_edit2 = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_edit2.sizePolicy().hasHeightForWidth())
        self.num_edit2.setSizePolicy(sizePolicy)
        self.num_edit2.setMaxLength(10)
        self.num_edit2.setAlignment(QtCore.Qt.AlignCenter)
        self.num_edit2.setObjectName("num_edit2")
        self.gridLayout.addWidget(self.num_edit2, 1, 0, 1, 1)
        self.num_chk2 = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_chk2.sizePolicy().hasHeightForWidth())
        self.num_chk2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.num_chk2.setFont(font)
        self.num_chk2.setObjectName("num_chk2")
        self.gridLayout.addWidget(self.num_chk2, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_19 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_11.addWidget(self.label_19)
        self.default_digital = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.default_digital.sizePolicy().hasHeightForWidth())
        self.default_digital.setSizePolicy(sizePolicy)
        self.default_digital.setMinimumSize(QtCore.QSize(0, 0))
        self.default_digital.setObjectName("default_digital")
        self.default_digital.addItem("")
        self.default_digital.addItem("")
        self.default_digital.addItem("")
        self.default_digital.addItem("")
        self.horizontalLayout_11.addWidget(self.default_digital)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(ConfigDialog)
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pres_edit1 = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pres_edit1.sizePolicy().hasHeightForWidth())
        self.pres_edit1.setSizePolicy(sizePolicy)
        self.pres_edit1.setMaxLength(10)
        self.pres_edit1.setAlignment(QtCore.Qt.AlignCenter)
        self.pres_edit1.setObjectName("pres_edit1")
        self.gridLayout_2.addWidget(self.pres_edit1, 0, 0, 1, 1)
        self.pres_chk1 = QtGui.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pres_chk1.setFont(font)
        self.pres_chk1.setObjectName("pres_chk1")
        self.gridLayout_2.addWidget(self.pres_chk1, 0, 1, 1, 1)
        self.pres_combo1 = QtGui.QComboBox(self.groupBox_2)
        self.pres_combo1.setObjectName("pres_combo1")
        self.pres_combo1.addItem("")
        self.pres_combo1.addItem("")
        self.pres_combo1.addItem("")
        self.pres_combo1.addItem("")
        self.pres_combo1.addItem("")
        self.gridLayout_2.addWidget(self.pres_combo1, 0, 2, 1, 1)
        self.pres_edit2 = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pres_edit2.sizePolicy().hasHeightForWidth())
        self.pres_edit2.setSizePolicy(sizePolicy)
        self.pres_edit2.setMaxLength(10)
        self.pres_edit2.setAlignment(QtCore.Qt.AlignCenter)
        self.pres_edit2.setObjectName("pres_edit2")
        self.gridLayout_2.addWidget(self.pres_edit2, 1, 0, 1, 1)
        self.pres_chk2 = QtGui.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pres_chk2.setFont(font)
        self.pres_chk2.setObjectName("pres_chk2")
        self.gridLayout_2.addWidget(self.pres_chk2, 1, 1, 1, 1)
        self.pres_combo2 = QtGui.QComboBox(self.groupBox_2)
        self.pres_combo2.setObjectName("pres_combo2")
        self.pres_combo2.addItem("")
        self.pres_combo2.addItem("")
        self.pres_combo2.addItem("")
        self.pres_combo2.addItem("")
        self.pres_combo2.addItem("")
        self.gridLayout_2.addWidget(self.pres_combo2, 1, 2, 1, 1)
        self.pres_edit3 = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pres_edit3.sizePolicy().hasHeightForWidth())
        self.pres_edit3.setSizePolicy(sizePolicy)
        self.pres_edit3.setMaxLength(10)
        self.pres_edit3.setAlignment(QtCore.Qt.AlignCenter)
        self.pres_edit3.setObjectName("pres_edit3")
        self.gridLayout_2.addWidget(self.pres_edit3, 2, 0, 1, 1)
        self.pres_chk3 = QtGui.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pres_chk3.setFont(font)
        self.pres_chk3.setObjectName("pres_chk3")
        self.gridLayout_2.addWidget(self.pres_chk3, 2, 1, 1, 1)
        self.pres_combo3 = QtGui.QComboBox(self.groupBox_2)
        self.pres_combo3.setObjectName("pres_combo3")
        self.pres_combo3.addItem("")
        self.pres_combo3.addItem("")
        self.pres_combo3.addItem("")
        self.pres_combo3.addItem("")
        self.pres_combo3.addItem("")
        self.gridLayout_2.addWidget(self.pres_combo3, 2, 2, 1, 1)
        self.pres_edit4 = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pres_edit4.sizePolicy().hasHeightForWidth())
        self.pres_edit4.setSizePolicy(sizePolicy)
        self.pres_edit4.setMaxLength(10)
        self.pres_edit4.setAlignment(QtCore.Qt.AlignCenter)
        self.pres_edit4.setObjectName("pres_edit4")
        self.gridLayout_2.addWidget(self.pres_edit4, 3, 0, 1, 1)
        self.pres_chk4 = QtGui.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pres_chk4.setFont(font)
        self.pres_chk4.setObjectName("pres_chk4")
        self.gridLayout_2.addWidget(self.pres_chk4, 3, 1, 1, 1)
        self.pres_combo4 = QtGui.QComboBox(self.groupBox_2)
        self.pres_combo4.setObjectName("pres_combo4")
        self.pres_combo4.addItem("")
        self.pres_combo4.addItem("")
        self.pres_combo4.addItem("")
        self.pres_combo4.addItem("")
        self.pres_combo4.addItem("")
        self.gridLayout_2.addWidget(self.pres_combo4, 3, 2, 1, 1)
        self.pres_edit5 = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pres_edit5.sizePolicy().hasHeightForWidth())
        self.pres_edit5.setSizePolicy(sizePolicy)
        self.pres_edit5.setMaxLength(10)
        self.pres_edit5.setAlignment(QtCore.Qt.AlignCenter)
        self.pres_edit5.setObjectName("pres_edit5")
        self.gridLayout_2.addWidget(self.pres_edit5, 4, 0, 1, 1)
        self.pres_chk5 = QtGui.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pres_chk5.setFont(font)
        self.pres_chk5.setObjectName("pres_chk5")
        self.gridLayout_2.addWidget(self.pres_chk5, 4, 1, 1, 1)
        self.pres_combo5 = QtGui.QComboBox(self.groupBox_2)
        self.pres_combo5.setObjectName("pres_combo5")
        self.pres_combo5.addItem("")
        self.pres_combo5.addItem("")
        self.pres_combo5.addItem("")
        self.pres_combo5.addItem("")
        self.pres_combo5.addItem("")
        self.gridLayout_2.addWidget(self.pres_combo5, 4, 2, 1, 1)
        self.pres_edit6 = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pres_edit6.sizePolicy().hasHeightForWidth())
        self.pres_edit6.setSizePolicy(sizePolicy)
        self.pres_edit6.setMaxLength(10)
        self.pres_edit6.setAlignment(QtCore.Qt.AlignCenter)
        self.pres_edit6.setObjectName("pres_edit6")
        self.gridLayout_2.addWidget(self.pres_edit6, 5, 0, 1, 1)
        self.pres_chk6 = QtGui.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pres_chk6.setFont(font)
        self.pres_chk6.setObjectName("pres_chk6")
        self.gridLayout_2.addWidget(self.pres_chk6, 5, 1, 1, 1)
        self.pres_combo6 = QtGui.QComboBox(self.groupBox_2)
        self.pres_combo6.setObjectName("pres_combo6")
        self.pres_combo6.addItem("")
        self.pres_combo6.addItem("")
        self.pres_combo6.addItem("")
        self.pres_combo6.addItem("")
        self.pres_combo6.addItem("")
        self.gridLayout_2.addWidget(self.pres_combo6, 5, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_7.addWidget(self.label_18)
        self.default_press = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.default_press.sizePolicy().hasHeightForWidth())
        self.default_press.setSizePolicy(sizePolicy)
        self.default_press.setModelColumn(0)
        self.default_press.setObjectName("default_press")
        self.default_press.addItem("")
        self.default_press.addItem("")
        self.default_press.addItem("")
        self.default_press.addItem("")
        self.default_press.addItem("")
        self.default_press.addItem("")
        self.horizontalLayout_7.addWidget(self.default_press)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.horizontalLayout_13.addLayout(self.verticalLayout_4)
        self.groupBox_4 = QtGui.QGroupBox(ConfigDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.speed_chk = QtGui.QCheckBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.speed_chk.setFont(font)
        self.speed_chk.setObjectName("speed_chk")
        self.horizontalLayout_5.addWidget(self.speed_chk)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.trigger_combo = QtGui.QComboBox(self.groupBox_4)
        self.trigger_combo.setMaxVisibleItems(3)
        self.trigger_combo.setObjectName("trigger_combo")
        self.trigger_combo.addItem("")
        self.trigger_combo.addItem("")
        self.trigger_combo.addItem("")
        self.horizontalLayout_6.addWidget(self.trigger_combo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        self.testProject = QtGui.QComboBox(self.groupBox_4)
        self.testProject.setObjectName("testProject")
        self.testProject.addItem("")
        self.testProject.addItem("")
        self.horizontalLayout_8.addWidget(self.testProject)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_17 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_9.addWidget(self.label_17)
        self.testTimer = QtGui.QSpinBox(self.groupBox_4)
        self.testTimer.setPrefix("")
        self.testTimer.setMinimum(0)
        self.testTimer.setProperty("value", 10)
        self.testTimer.setObjectName("testTimer")
        self.horizontalLayout_9.addWidget(self.testTimer)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_12.addWidget(self.label_20)
        self.test_shift = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.test_shift.setPrefix("")
        self.test_shift.setProperty("value", 7.0)
        self.test_shift.setObjectName("test_shift")
        self.horizontalLayout_12.addWidget(self.test_shift)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.projectName_edit = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projectName_edit.sizePolicy().hasHeightForWidth())
        self.projectName_edit.setSizePolicy(sizePolicy)
        self.projectName_edit.setMaxLength(15)
        self.projectName_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.projectName_edit.setObjectName("projectName_edit")
        self.horizontalLayout.addWidget(self.projectName_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.person_edit = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.person_edit.sizePolicy().hasHeightForWidth())
        self.person_edit.setSizePolicy(sizePolicy)
        self.person_edit.setMaxLength(15)
        self.person_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.person_edit.setObjectName("person_edit")
        self.horizontalLayout_2.addWidget(self.person_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_3.addWidget(self.label_15)
        self.time_edit = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_edit.sizePolicy().hasHeightForWidth())
        self.time_edit.setSizePolicy(sizePolicy)
        self.time_edit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.time_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.time_edit.setReadOnly(True)
        self.time_edit.setObjectName("time_edit")
        self.horizontalLayout_3.addWidget(self.time_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.loadConfigButton = QtGui.QPushButton(self.groupBox_4)
        self.loadConfigButton.setCursor(QtCore.Qt.PointingHandCursor)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/Load-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadConfigButton.setIcon(icon1)
        self.loadConfigButton.setIconSize(QtCore.QSize(32, 32))
        self.loadConfigButton.setShortcut("")
        self.loadConfigButton.setAutoDefault(True)
        self.loadConfigButton.setDefault(False)
        self.loadConfigButton.setFlat(False)
        self.loadConfigButton.setObjectName("loadConfigButton")
        self.horizontalLayout_4.addWidget(self.loadConfigButton)
        spacerItem1 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.saveConfigButton = QtGui.QPushButton(self.groupBox_4)
        self.saveConfigButton.setCursor(QtCore.Qt.PointingHandCursor)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/Save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveConfigButton.setIcon(icon2)
        self.saveConfigButton.setIconSize(QtCore.QSize(32, 32))
        self.saveConfigButton.setAutoDefault(True)
        self.saveConfigButton.setDefault(False)
        self.saveConfigButton.setObjectName("saveConfigButton")
        self.horizontalLayout_4.addWidget(self.saveConfigButton)
        spacerItem2 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_13.addWidget(self.groupBox_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.clearButton = QtGui.QPushButton(ConfigDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearButton.sizePolicy().hasHeightForWidth())
        self.clearButton.setSizePolicy(sizePolicy)
        self.clearButton.setMinimumSize(QtCore.QSize(140, 55))
        self.clearButton.setMaximumSize(QtCore.QSize(140, 55))
        self.clearButton.setCursor(QtCore.Qt.PointingHandCursor)
        self.clearButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/image/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearButton.setIcon(icon3)
        self.clearButton.setIconSize(QtCore.QSize(48, 48))
        self.clearButton.setShortcut("")
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_10.addWidget(self.clearButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.calibrationButton = QtGui.QPushButton(ConfigDialog)
        self.calibrationButton.setMinimumSize(QtCore.QSize(140, 55))
        self.calibrationButton.setMaximumSize(QtCore.QSize(140, 55))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/image/calibration.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calibrationButton.setIcon(icon4)
        self.calibrationButton.setIconSize(QtCore.QSize(48, 48))
        self.calibrationButton.setObjectName("calibrationButton")
        self.horizontalLayout_10.addWidget(self.calibrationButton)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.matchButton = QtGui.QPushButton(ConfigDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matchButton.sizePolicy().hasHeightForWidth())
        self.matchButton.setSizePolicy(sizePolicy)
        self.matchButton.setMinimumSize(QtCore.QSize(140, 55))
        self.matchButton.setMaximumSize(QtCore.QSize(140, 55))
        self.matchButton.setCursor(QtCore.Qt.PointingHandCursor)
        self.matchButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/image/link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.matchButton.setIcon(icon5)
        self.matchButton.setIconSize(QtCore.QSize(48, 48))
        self.matchButton.setShortcut("")
        self.matchButton.setAutoDefault(False)
        self.matchButton.setDefault(True)
        self.matchButton.setObjectName("matchButton")
        self.horizontalLayout_10.addWidget(self.matchButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)

        self.retranslateUi(ConfigDialog)
        self.default_digital.setCurrentIndex(0)
        self.pres_combo1.setCurrentIndex(1)
        self.pres_combo2.setCurrentIndex(1)
        self.pres_combo3.setCurrentIndex(1)
        self.pres_combo4.setCurrentIndex(1)
        self.pres_combo5.setCurrentIndex(1)
        self.pres_combo6.setCurrentIndex(1)
        self.trigger_combo.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ConfigDialog)
        ConfigDialog.setTabOrder(self.num_edit1, self.num_chk1)
        ConfigDialog.setTabOrder(self.num_chk1, self.num_edit2)
        ConfigDialog.setTabOrder(self.num_edit2, self.num_chk2)
        ConfigDialog.setTabOrder(self.num_chk2, self.num_edit3)
        ConfigDialog.setTabOrder(self.num_edit3, self.num_chk3)
        ConfigDialog.setTabOrder(self.num_chk3, self.num_edit4)
        ConfigDialog.setTabOrder(self.num_edit4, self.num_chk4)
        ConfigDialog.setTabOrder(self.num_chk4, self.default_digital)
        ConfigDialog.setTabOrder(self.default_digital, self.pres_edit1)
        ConfigDialog.setTabOrder(self.pres_edit1, self.pres_chk1)
        ConfigDialog.setTabOrder(self.pres_chk1, self.pres_combo1)
        ConfigDialog.setTabOrder(self.pres_combo1, self.pres_edit2)
        ConfigDialog.setTabOrder(self.pres_edit2, self.pres_chk2)
        ConfigDialog.setTabOrder(self.pres_chk2, self.pres_combo2)
        ConfigDialog.setTabOrder(self.pres_combo2, self.pres_edit3)
        ConfigDialog.setTabOrder(self.pres_edit3, self.pres_chk3)
        ConfigDialog.setTabOrder(self.pres_chk3, self.pres_combo3)
        ConfigDialog.setTabOrder(self.pres_combo3, self.pres_edit4)
        ConfigDialog.setTabOrder(self.pres_edit4, self.pres_chk4)
        ConfigDialog.setTabOrder(self.pres_chk4, self.pres_combo4)
        ConfigDialog.setTabOrder(self.pres_combo4, self.pres_edit5)
        ConfigDialog.setTabOrder(self.pres_edit5, self.pres_chk5)
        ConfigDialog.setTabOrder(self.pres_chk5, self.pres_combo5)
        ConfigDialog.setTabOrder(self.pres_combo5, self.pres_edit6)
        ConfigDialog.setTabOrder(self.pres_edit6, self.pres_chk6)
        ConfigDialog.setTabOrder(self.pres_chk6, self.pres_combo6)
        ConfigDialog.setTabOrder(self.pres_combo6, self.default_press)
        ConfigDialog.setTabOrder(self.default_press, self.speed_chk)
        ConfigDialog.setTabOrder(self.speed_chk, self.trigger_combo)
        ConfigDialog.setTabOrder(self.trigger_combo, self.testProject)
        ConfigDialog.setTabOrder(self.testProject, self.testTimer)
        ConfigDialog.setTabOrder(self.testTimer, self.test_shift)
        ConfigDialog.setTabOrder(self.test_shift, self.projectName_edit)
        ConfigDialog.setTabOrder(self.projectName_edit, self.person_edit)
        ConfigDialog.setTabOrder(self.person_edit, self.loadConfigButton)
        ConfigDialog.setTabOrder(self.loadConfigButton, self.saveConfigButton)
        ConfigDialog.setTabOrder(self.saveConfigButton, self.matchButton)

    def retranslateUi(self, ConfigDialog):
        ConfigDialog.setWindowTitle(QtGui.QApplication.translate("ConfigDialog", "配置修改", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ConfigDialog", "数字量/计时", None, QtGui.QApplication.UnicodeUTF8))
        self.num_chk4.setText(QtGui.QApplication.translate("ConfigDialog", "通道4", None, QtGui.QApplication.UnicodeUTF8))
        self.num_chk3.setText(QtGui.QApplication.translate("ConfigDialog", "通道3", None, QtGui.QApplication.UnicodeUTF8))
        self.num_chk1.setText(QtGui.QApplication.translate("ConfigDialog", "通道1", None, QtGui.QApplication.UnicodeUTF8))
        self.num_chk2.setText(QtGui.QApplication.translate("ConfigDialog", "通道2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("ConfigDialog", "计量通道", None, QtGui.QApplication.UnicodeUTF8))
        self.default_digital.setItemText(0, QtGui.QApplication.translate("ConfigDialog", "通  道       1", None, QtGui.QApplication.UnicodeUTF8))
        self.default_digital.setItemText(1, QtGui.QApplication.translate("ConfigDialog", "通  道       2", None, QtGui.QApplication.UnicodeUTF8))
        self.default_digital.setItemText(2, QtGui.QApplication.translate("ConfigDialog", "通  道       3", None, QtGui.QApplication.UnicodeUTF8))
        self.default_digital.setItemText(3, QtGui.QApplication.translate("ConfigDialog", "通  道       4", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ConfigDialog", "压力", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_chk1.setText(QtGui.QApplication.translate("ConfigDialog", "通道1", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo1.setItemText(0, QtGui.QApplication.translate("ConfigDialog", "40Mpa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo1.setItemText(1, QtGui.QApplication.translate("ConfigDialog", "10MPa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo1.setItemText(2, QtGui.QApplication.translate("ConfigDialog", "5MPa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo1.setItemText(3, QtGui.QApplication.translate("ConfigDialog", "2Mpa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo1.setItemText(4, QtGui.QApplication.translate("ConfigDialog", "1MPa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_chk2.setText(QtGui.QApplication.translate("ConfigDialog", "通道2", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo2.setItemText(0, QtGui.QApplication.translate("ConfigDialog", "40Mpa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo2.setItemText(1, QtGui.QApplication.translate("ConfigDialog", "10MPa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo2.setItemText(2, QtGui.QApplication.translate("ConfigDialog", "5MPa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo2.setItemText(3, QtGui.QApplication.translate("ConfigDialog", "2Mpa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo2.setItemText(4, QtGui.QApplication.translate("ConfigDialog", "1MPa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_chk3.setText(QtGui.QApplication.translate("ConfigDialog", "通道3", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo3.setItemText(0, QtGui.QApplication.translate("ConfigDialog", "40Mpa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo3.setItemText(1, QtGui.QApplication.translate("ConfigDialog", "10MPa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo3.setItemText(2, QtGui.QApplication.translate("ConfigDialog", "5MPa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo3.setItemText(3, QtGui.QApplication.translate("ConfigDialog", "2Mpa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo3.setItemText(4, QtGui.QApplication.translate("ConfigDialog", "1MPa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_chk4.setText(QtGui.QApplication.translate("ConfigDialog", "通道4", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo4.setItemText(0, QtGui.QApplication.translate("ConfigDialog", "40Mpa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo4.setItemText(1, QtGui.QApplication.translate("ConfigDialog", "10MPa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo4.setItemText(2, QtGui.QApplication.translate("ConfigDialog", "5MPa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo4.setItemText(3, QtGui.QApplication.translate("ConfigDialog", "2Mpa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo4.setItemText(4, QtGui.QApplication.translate("ConfigDialog", "1MPa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_chk5.setText(QtGui.QApplication.translate("ConfigDialog", "通道5", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo5.setItemText(0, QtGui.QApplication.translate("ConfigDialog", "40Mpa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo5.setItemText(1, QtGui.QApplication.translate("ConfigDialog", "10MPa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo5.setItemText(2, QtGui.QApplication.translate("ConfigDialog", "5MPa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo5.setItemText(3, QtGui.QApplication.translate("ConfigDialog", "2Mpa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo5.setItemText(4, QtGui.QApplication.translate("ConfigDialog", "1MPa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_chk6.setText(QtGui.QApplication.translate("ConfigDialog", "通道6", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo6.setItemText(0, QtGui.QApplication.translate("ConfigDialog", "40Mpa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo6.setItemText(1, QtGui.QApplication.translate("ConfigDialog", "10MPa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo6.setItemText(2, QtGui.QApplication.translate("ConfigDialog", "5MPa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo6.setItemText(3, QtGui.QApplication.translate("ConfigDialog", "2Mpa", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_combo6.setItemText(4, QtGui.QApplication.translate("ConfigDialog", "1MPa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("ConfigDialog", "计量通道", None, QtGui.QApplication.UnicodeUTF8))
        self.default_press.setItemText(0, QtGui.QApplication.translate("ConfigDialog", "通  道       1", None, QtGui.QApplication.UnicodeUTF8))
        self.default_press.setItemText(1, QtGui.QApplication.translate("ConfigDialog", "通  道       2", None, QtGui.QApplication.UnicodeUTF8))
        self.default_press.setItemText(2, QtGui.QApplication.translate("ConfigDialog", "通  道       3", None, QtGui.QApplication.UnicodeUTF8))
        self.default_press.setItemText(3, QtGui.QApplication.translate("ConfigDialog", "通  道       4", None, QtGui.QApplication.UnicodeUTF8))
        self.default_press.setItemText(4, QtGui.QApplication.translate("ConfigDialog", "通  道       5", None, QtGui.QApplication.UnicodeUTF8))
        self.default_press.setItemText(5, QtGui.QApplication.translate("ConfigDialog", "通  道       6", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("ConfigDialog", "操作", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("ConfigDialog", "速度通道", None, QtGui.QApplication.UnicodeUTF8))
        self.speed_chk.setText(QtGui.QApplication.translate("ConfigDialog", "使用", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("ConfigDialog", "触发方式", None, QtGui.QApplication.UnicodeUTF8))
        self.trigger_combo.setItemText(0, QtGui.QApplication.translate("ConfigDialog", "自动触发", None, QtGui.QApplication.UnicodeUTF8))
        self.trigger_combo.setItemText(1, QtGui.QApplication.translate("ConfigDialog", "手动触发", None, QtGui.QApplication.UnicodeUTF8))
        self.trigger_combo.setItemText(2, QtGui.QApplication.translate("ConfigDialog", "外触发", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("ConfigDialog", "测试类型", None, QtGui.QApplication.UnicodeUTF8))
        self.testProject.setItemText(0, QtGui.QApplication.translate("ConfigDialog", "鱼雷", None, QtGui.QApplication.UnicodeUTF8))
        self.testProject.setItemText(1, QtGui.QApplication.translate("ConfigDialog", "诱饵", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("ConfigDialog", "测试时间", None, QtGui.QApplication.UnicodeUTF8))
        self.testTimer.setSuffix(QtGui.QApplication.translate("ConfigDialog", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("ConfigDialog", "位移设置", None, QtGui.QApplication.UnicodeUTF8))
        self.test_shift.setSuffix(QtGui.QApplication.translate("ConfigDialog", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("ConfigDialog", "测试编号", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("ConfigDialog", "测试人员", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("ConfigDialog", "测试日期", None, QtGui.QApplication.UnicodeUTF8))
        self.loadConfigButton.setText(QtGui.QApplication.translate("ConfigDialog", "载入配置", None, QtGui.QApplication.UnicodeUTF8))
        self.saveConfigButton.setText(QtGui.QApplication.translate("ConfigDialog", "保存配置", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("ConfigDialog", "清空", None, QtGui.QApplication.UnicodeUTF8))
        self.calibrationButton.setText(QtGui.QApplication.translate("ConfigDialog", "压力校准", None, QtGui.QApplication.UnicodeUTF8))
        self.matchButton.setText(QtGui.QApplication.translate("ConfigDialog", "检测匹配连接", None, QtGui.QApplication.UnicodeUTF8))

import Icons_rc
import Lang_rc
