# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_designer\Configuration.ui'
#
# Created: Tue Oct 29 11:06:02 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Configuration(object):
    def setupUi(self, Configuration):
        Configuration.setObjectName("Configuration")
        Configuration.resize(164, 498)
        self.verticalLayout = QtGui.QVBoxLayout(Configuration)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtGui.QLabel(Configuration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.groupBox_2 = QtGui.QGroupBox(Configuration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dswitch_lbl3 = QtGui.QLabel(self.groupBox_2)
        self.dswitch_lbl3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dswitch_lbl3.setObjectName("dswitch_lbl3")
        self.gridLayout_2.addWidget(self.dswitch_lbl3, 2, 1, 1, 1)
        self.dchannel_lbl3 = QtGui.QLabel(self.groupBox_2)
        self.dchannel_lbl3.setObjectName("dchannel_lbl3")
        self.gridLayout_2.addWidget(self.dchannel_lbl3, 2, 0, 1, 1)
        self.dswitch_lbl2 = QtGui.QLabel(self.groupBox_2)
        self.dswitch_lbl2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dswitch_lbl2.setObjectName("dswitch_lbl2")
        self.gridLayout_2.addWidget(self.dswitch_lbl2, 1, 1, 1, 1)
        self.dswitch_lbl1 = QtGui.QLabel(self.groupBox_2)
        self.dswitch_lbl1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dswitch_lbl1.setObjectName("dswitch_lbl1")
        self.gridLayout_2.addWidget(self.dswitch_lbl1, 0, 1, 1, 1)
        self.dchannel_lbl4 = QtGui.QLabel(self.groupBox_2)
        self.dchannel_lbl4.setObjectName("dchannel_lbl4")
        self.gridLayout_2.addWidget(self.dchannel_lbl4, 3, 0, 1, 1)
        self.dchannel_lbl2 = QtGui.QLabel(self.groupBox_2)
        self.dchannel_lbl2.setObjectName("dchannel_lbl2")
        self.gridLayout_2.addWidget(self.dchannel_lbl2, 1, 0, 1, 1)
        self.dswitch_lbl4 = QtGui.QLabel(self.groupBox_2)
        self.dswitch_lbl4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dswitch_lbl4.setObjectName("dswitch_lbl4")
        self.gridLayout_2.addWidget(self.dswitch_lbl4, 3, 1, 1, 1)
        self.dchannel_lbl1 = QtGui.QLabel(self.groupBox_2)
        self.dchannel_lbl1.setObjectName("dchannel_lbl1")
        self.gridLayout_2.addWidget(self.dchannel_lbl1, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(Configuration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.pswitch_lbl1 = QtGui.QLabel(self.groupBox)
        self.pswitch_lbl1.setFrameShape(QtGui.QFrame.NoFrame)
        self.pswitch_lbl1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pswitch_lbl1.setObjectName("pswitch_lbl1")
        self.gridLayout.addWidget(self.pswitch_lbl1, 0, 2, 1, 1)
        self.prange_lbl5 = QtGui.QLabel(self.groupBox)
        self.prange_lbl5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prange_lbl5.setObjectName("prange_lbl5")
        self.gridLayout.addWidget(self.prange_lbl5, 4, 1, 1, 1)
        self.prange_lbl1 = QtGui.QLabel(self.groupBox)
        self.prange_lbl1.setFrameShape(QtGui.QFrame.NoFrame)
        self.prange_lbl1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prange_lbl1.setObjectName("prange_lbl1")
        self.gridLayout.addWidget(self.prange_lbl1, 0, 1, 1, 1)
        self.pchannel_lbl6 = QtGui.QLabel(self.groupBox)
        self.pchannel_lbl6.setObjectName("pchannel_lbl6")
        self.gridLayout.addWidget(self.pchannel_lbl6, 5, 0, 1, 1)
        self.pswitch_lbl4 = QtGui.QLabel(self.groupBox)
        self.pswitch_lbl4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pswitch_lbl4.setObjectName("pswitch_lbl4")
        self.gridLayout.addWidget(self.pswitch_lbl4, 3, 2, 1, 1)
        self.pswitch_lbl5 = QtGui.QLabel(self.groupBox)
        self.pswitch_lbl5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pswitch_lbl5.setObjectName("pswitch_lbl5")
        self.gridLayout.addWidget(self.pswitch_lbl5, 4, 2, 1, 1)
        self.prange_lbl6 = QtGui.QLabel(self.groupBox)
        self.prange_lbl6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prange_lbl6.setObjectName("prange_lbl6")
        self.gridLayout.addWidget(self.prange_lbl6, 5, 1, 1, 1)
        self.pswitch_lbl6 = QtGui.QLabel(self.groupBox)
        self.pswitch_lbl6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pswitch_lbl6.setObjectName("pswitch_lbl6")
        self.gridLayout.addWidget(self.pswitch_lbl6, 5, 2, 1, 1)
        self.prange_lbl2 = QtGui.QLabel(self.groupBox)
        self.prange_lbl2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prange_lbl2.setObjectName("prange_lbl2")
        self.gridLayout.addWidget(self.prange_lbl2, 1, 1, 1, 1)
        self.pchannel_lbl3 = QtGui.QLabel(self.groupBox)
        self.pchannel_lbl3.setObjectName("pchannel_lbl3")
        self.gridLayout.addWidget(self.pchannel_lbl3, 2, 0, 1, 1)
        self.pchannel_lbl5 = QtGui.QLabel(self.groupBox)
        self.pchannel_lbl5.setObjectName("pchannel_lbl5")
        self.gridLayout.addWidget(self.pchannel_lbl5, 4, 0, 1, 1)
        self.pswitch_lbl3 = QtGui.QLabel(self.groupBox)
        self.pswitch_lbl3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pswitch_lbl3.setObjectName("pswitch_lbl3")
        self.gridLayout.addWidget(self.pswitch_lbl3, 2, 2, 1, 1)
        self.pchannel_lbl1 = QtGui.QLabel(self.groupBox)
        self.pchannel_lbl1.setFrameShape(QtGui.QFrame.NoFrame)
        self.pchannel_lbl1.setFrameShadow(QtGui.QFrame.Sunken)
        self.pchannel_lbl1.setObjectName("pchannel_lbl1")
        self.gridLayout.addWidget(self.pchannel_lbl1, 0, 0, 1, 1)
        self.pchannel_lbl4 = QtGui.QLabel(self.groupBox)
        self.pchannel_lbl4.setObjectName("pchannel_lbl4")
        self.gridLayout.addWidget(self.pchannel_lbl4, 3, 0, 1, 1)
        self.prange_lbl3 = QtGui.QLabel(self.groupBox)
        self.prange_lbl3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prange_lbl3.setObjectName("prange_lbl3")
        self.gridLayout.addWidget(self.prange_lbl3, 2, 1, 1, 1)
        self.prange_lbl4 = QtGui.QLabel(self.groupBox)
        self.prange_lbl4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prange_lbl4.setObjectName("prange_lbl4")
        self.gridLayout.addWidget(self.prange_lbl4, 3, 1, 1, 1)
        self.pchannel_lbl2 = QtGui.QLabel(self.groupBox)
        self.pchannel_lbl2.setObjectName("pchannel_lbl2")
        self.gridLayout.addWidget(self.pchannel_lbl2, 1, 0, 1, 1)
        self.pswitch_lbl2 = QtGui.QLabel(self.groupBox)
        self.pswitch_lbl2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pswitch_lbl2.setObjectName("pswitch_lbl2")
        self.gridLayout.addWidget(self.pswitch_lbl2, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(Configuration)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.speed_lbl = QtGui.QLabel(self.groupBox_3)
        self.speed_lbl.setObjectName("speed_lbl")
        self.gridLayout_3.addWidget(self.speed_lbl, 0, 0, 1, 1)
        self.spswitch_lbl = QtGui.QLabel(self.groupBox_3)
        self.spswitch_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spswitch_lbl.setObjectName("spswitch_lbl")
        self.gridLayout_3.addWidget(self.spswitch_lbl, 0, 1, 1, 1)
        self.distance_lbl = QtGui.QLabel(self.groupBox_3)
        self.distance_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.distance_lbl.setObjectName("distance_lbl")
        self.gridLayout_3.addWidget(self.distance_lbl, 3, 1, 1, 1)
        self.time_lbl = QtGui.QLabel(self.groupBox_3)
        self.time_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time_lbl.setObjectName("time_lbl")
        self.gridLayout_3.addWidget(self.time_lbl, 2, 1, 1, 1)
        self.ttime_lbl = QtGui.QLabel(self.groupBox_3)
        self.ttime_lbl.setObjectName("ttime_lbl")
        self.gridLayout_3.addWidget(self.ttime_lbl, 2, 0, 1, 1)
        self.ddistance_lbl = QtGui.QLabel(self.groupBox_3)
        self.ddistance_lbl.setObjectName("ddistance_lbl")
        self.gridLayout_3.addWidget(self.ddistance_lbl, 3, 0, 1, 1)
        self.tri_lbl = QtGui.QLabel(self.groupBox_3)
        self.tri_lbl.setObjectName("tri_lbl")
        self.gridLayout_3.addWidget(self.tri_lbl, 1, 0, 1, 1)
        self.trigger_lbl = QtGui.QLabel(self.groupBox_3)
        self.trigger_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.trigger_lbl.setObjectName("trigger_lbl")
        self.gridLayout_3.addWidget(self.trigger_lbl, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)

        self.retranslateUi(Configuration)
        QtCore.QMetaObject.connectSlotsByName(Configuration)

    def retranslateUi(self, Configuration):
        Configuration.setWindowTitle(QtGui.QApplication.translate("Configuration", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Configuration", "<html><head/><body><p><span style=\" font-size:14pt;\">配置信息</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Configuration", "数字量/计时", None, QtGui.QApplication.UnicodeUTF8))
        self.dswitch_lbl3.setText(QtGui.QApplication.translate("Configuration", "关闭", None, QtGui.QApplication.UnicodeUTF8))
        self.dchannel_lbl3.setText(QtGui.QApplication.translate("Configuration", "通道3", None, QtGui.QApplication.UnicodeUTF8))
        self.dswitch_lbl2.setText(QtGui.QApplication.translate("Configuration", "关闭", None, QtGui.QApplication.UnicodeUTF8))
        self.dswitch_lbl1.setText(QtGui.QApplication.translate("Configuration", "关闭", None, QtGui.QApplication.UnicodeUTF8))
        self.dchannel_lbl4.setText(QtGui.QApplication.translate("Configuration", "通道4", None, QtGui.QApplication.UnicodeUTF8))
        self.dchannel_lbl2.setText(QtGui.QApplication.translate("Configuration", "通道2", None, QtGui.QApplication.UnicodeUTF8))
        self.dswitch_lbl4.setText(QtGui.QApplication.translate("Configuration", "关闭", None, QtGui.QApplication.UnicodeUTF8))
        self.dchannel_lbl1.setText(QtGui.QApplication.translate("Configuration", "通道1", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Configuration", "压力", None, QtGui.QApplication.UnicodeUTF8))
        self.pswitch_lbl1.setText(QtGui.QApplication.translate("Configuration", "关闭", None, QtGui.QApplication.UnicodeUTF8))
        self.prange_lbl5.setText(QtGui.QApplication.translate("Configuration", "10Mpa", None, QtGui.QApplication.UnicodeUTF8))
        self.prange_lbl1.setText(QtGui.QApplication.translate("Configuration", "10Mpa", None, QtGui.QApplication.UnicodeUTF8))
        self.pchannel_lbl6.setText(QtGui.QApplication.translate("Configuration", "通道6", None, QtGui.QApplication.UnicodeUTF8))
        self.pswitch_lbl4.setText(QtGui.QApplication.translate("Configuration", "关闭", None, QtGui.QApplication.UnicodeUTF8))
        self.pswitch_lbl5.setText(QtGui.QApplication.translate("Configuration", "关闭", None, QtGui.QApplication.UnicodeUTF8))
        self.prange_lbl6.setText(QtGui.QApplication.translate("Configuration", "10Mpa", None, QtGui.QApplication.UnicodeUTF8))
        self.pswitch_lbl6.setText(QtGui.QApplication.translate("Configuration", "关闭", None, QtGui.QApplication.UnicodeUTF8))
        self.prange_lbl2.setText(QtGui.QApplication.translate("Configuration", "10Mpa", None, QtGui.QApplication.UnicodeUTF8))
        self.pchannel_lbl3.setText(QtGui.QApplication.translate("Configuration", "通道3", None, QtGui.QApplication.UnicodeUTF8))
        self.pchannel_lbl5.setText(QtGui.QApplication.translate("Configuration", "通道5", None, QtGui.QApplication.UnicodeUTF8))
        self.pswitch_lbl3.setText(QtGui.QApplication.translate("Configuration", "关闭", None, QtGui.QApplication.UnicodeUTF8))
        self.pchannel_lbl1.setText(QtGui.QApplication.translate("Configuration", "通道1", None, QtGui.QApplication.UnicodeUTF8))
        self.pchannel_lbl4.setText(QtGui.QApplication.translate("Configuration", "通道4", None, QtGui.QApplication.UnicodeUTF8))
        self.prange_lbl3.setText(QtGui.QApplication.translate("Configuration", "10Mpa", None, QtGui.QApplication.UnicodeUTF8))
        self.prange_lbl4.setText(QtGui.QApplication.translate("Configuration", "10Mpa", None, QtGui.QApplication.UnicodeUTF8))
        self.pchannel_lbl2.setText(QtGui.QApplication.translate("Configuration", "通道2", None, QtGui.QApplication.UnicodeUTF8))
        self.pswitch_lbl2.setText(QtGui.QApplication.translate("Configuration", "关闭", None, QtGui.QApplication.UnicodeUTF8))
        self.speed_lbl.setText(QtGui.QApplication.translate("Configuration", "速度", None, QtGui.QApplication.UnicodeUTF8))
        self.spswitch_lbl.setText(QtGui.QApplication.translate("Configuration", "关闭", None, QtGui.QApplication.UnicodeUTF8))
        self.distance_lbl.setText(QtGui.QApplication.translate("Configuration", "7.0m", None, QtGui.QApplication.UnicodeUTF8))
        self.time_lbl.setText(QtGui.QApplication.translate("Configuration", "10s", None, QtGui.QApplication.UnicodeUTF8))
        self.ttime_lbl.setText(QtGui.QApplication.translate("Configuration", "测试时间", None, QtGui.QApplication.UnicodeUTF8))
        self.ddistance_lbl.setText(QtGui.QApplication.translate("Configuration", "测试位移", None, QtGui.QApplication.UnicodeUTF8))
        self.tri_lbl.setText(QtGui.QApplication.translate("Configuration", "触发类型", None, QtGui.QApplication.UnicodeUTF8))
        self.trigger_lbl.setText(QtGui.QApplication.translate("Configuration", "自动触发", None, QtGui.QApplication.UnicodeUTF8))

import Icons_rc
