# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_designer\LCDGroup.ui'
#
# Created: Tue Oct 29 11:06:02 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_LCDGroup(object):
    def setupUi(self, LCDGroup):
        LCDGroup.setObjectName("LCDGroup")
        LCDGroup.resize(148, 533)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LCDGroup.sizePolicy().hasHeightForWidth())
        LCDGroup.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(LCDGroup)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.st_transfer = QtGui.QPushButton(LCDGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.st_transfer.sizePolicy().hasHeightForWidth())
        self.st_transfer.setSizePolicy(sizePolicy)
        self.st_transfer.setStyleSheet("QPushButton#st_transfer {\n"
"    font: 10pt;\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0.05                     #77d42a, stop:1 #5cb811);\n"
"    border-style:outset;\n"
"    border-width:1px;\n"
"    border-radius:8px;\n"
"    border-color:#636363;\n"
"    padding:8px\n"
"}\n"
"\n"
"QPushButton#st_transfer:hover{\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0.05                     #5cb811, stop:1 #77d42a);\n"
"}\n"
"\n"
"QPushButton#st_transfer:pressed {\n"
"     background: #adff2f;\n"
"     border-style: inset;}")
        self.st_transfer.setAutoRepeatDelay(300)
        self.st_transfer.setAutoDefault(False)
        self.st_transfer.setObjectName("st_transfer")
        self.verticalLayout.addWidget(self.st_transfer)
        self.group_press = QtGui.QGroupBox(LCDGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_press.sizePolicy().hasHeightForWidth())
        self.group_press.setSizePolicy(sizePolicy)
        self.group_press.setObjectName("group_press")
        self.formLayout = QtGui.QFormLayout(self.group_press)
        self.formLayout.setContentsMargins(2, 2, 2, 2)
        self.formLayout.setHorizontalSpacing(2)
        self.formLayout.setVerticalSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.press_chk1 = QtGui.QCheckBox(self.group_press)
        self.press_chk1.setObjectName("press_chk1")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.press_chk1)
        self.press_lcd1 = QtGui.QLCDNumber(self.group_press)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.press_lcd1.sizePolicy().hasHeightForWidth())
        self.press_lcd1.setSizePolicy(sizePolicy)
        self.press_lcd1.setSmallDecimalPoint(False)
        self.press_lcd1.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.press_lcd1.setObjectName("press_lcd1")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.press_lcd1)
        self.press_chk2 = QtGui.QCheckBox(self.group_press)
        self.press_chk2.setObjectName("press_chk2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.press_chk2)
        self.press_lcd2 = QtGui.QLCDNumber(self.group_press)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.press_lcd2.sizePolicy().hasHeightForWidth())
        self.press_lcd2.setSizePolicy(sizePolicy)
        self.press_lcd2.setSmallDecimalPoint(False)
        self.press_lcd2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.press_lcd2.setObjectName("press_lcd2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.press_lcd2)
        self.press_chk3 = QtGui.QCheckBox(self.group_press)
        self.press_chk3.setObjectName("press_chk3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.press_chk3)
        self.press_lcd3 = QtGui.QLCDNumber(self.group_press)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.press_lcd3.sizePolicy().hasHeightForWidth())
        self.press_lcd3.setSizePolicy(sizePolicy)
        self.press_lcd3.setSmallDecimalPoint(False)
        self.press_lcd3.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.press_lcd3.setObjectName("press_lcd3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.press_lcd3)
        self.press_chk4 = QtGui.QCheckBox(self.group_press)
        self.press_chk4.setObjectName("press_chk4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.press_chk4)
        self.press_lcd4 = QtGui.QLCDNumber(self.group_press)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.press_lcd4.sizePolicy().hasHeightForWidth())
        self.press_lcd4.setSizePolicy(sizePolicy)
        self.press_lcd4.setSmallDecimalPoint(False)
        self.press_lcd4.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.press_lcd4.setObjectName("press_lcd4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.press_lcd4)
        self.press_chk5 = QtGui.QCheckBox(self.group_press)
        self.press_chk5.setObjectName("press_chk5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.press_chk5)
        self.press_lcd5 = QtGui.QLCDNumber(self.group_press)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.press_lcd5.sizePolicy().hasHeightForWidth())
        self.press_lcd5.setSizePolicy(sizePolicy)
        self.press_lcd5.setSmallDecimalPoint(False)
        self.press_lcd5.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.press_lcd5.setObjectName("press_lcd5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.press_lcd5)
        self.press_chk6 = QtGui.QCheckBox(self.group_press)
        self.press_chk6.setObjectName("press_chk6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.press_chk6)
        self.press_lcd6 = QtGui.QLCDNumber(self.group_press)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.press_lcd6.sizePolicy().hasHeightForWidth())
        self.press_lcd6.setSizePolicy(sizePolicy)
        self.press_lcd6.setSmallDecimalPoint(False)
        self.press_lcd6.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.press_lcd6.setObjectName("press_lcd6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.press_lcd6)
        self.verticalLayout.addWidget(self.group_press)
        self.group_digital = QtGui.QGroupBox(LCDGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_digital.sizePolicy().hasHeightForWidth())
        self.group_digital.setSizePolicy(sizePolicy)
        self.group_digital.setObjectName("group_digital")
        self.formLayout_2 = QtGui.QFormLayout(self.group_digital)
        self.formLayout_2.setContentsMargins(2, 2, 2, 2)
        self.formLayout_2.setHorizontalSpacing(2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.digital_chk1 = QtGui.QCheckBox(self.group_digital)
        self.digital_chk1.setObjectName("digital_chk1")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.digital_chk1)
        self.digital_lcd1 = QtGui.QLCDNumber(self.group_digital)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.digital_lcd1.sizePolicy().hasHeightForWidth())
        self.digital_lcd1.setSizePolicy(sizePolicy)
        self.digital_lcd1.setSmallDecimalPoint(False)
        self.digital_lcd1.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.digital_lcd1.setObjectName("digital_lcd1")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.digital_lcd1)
        self.digital_chk2 = QtGui.QCheckBox(self.group_digital)
        self.digital_chk2.setObjectName("digital_chk2")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.digital_chk2)
        self.digital_lcd2 = QtGui.QLCDNumber(self.group_digital)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.digital_lcd2.sizePolicy().hasHeightForWidth())
        self.digital_lcd2.setSizePolicy(sizePolicy)
        self.digital_lcd2.setSmallDecimalPoint(False)
        self.digital_lcd2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.digital_lcd2.setObjectName("digital_lcd2")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.digital_lcd2)
        self.digital_chk3 = QtGui.QCheckBox(self.group_digital)
        self.digital_chk3.setObjectName("digital_chk3")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.digital_chk3)
        self.digital_lcd3 = QtGui.QLCDNumber(self.group_digital)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.digital_lcd3.sizePolicy().hasHeightForWidth())
        self.digital_lcd3.setSizePolicy(sizePolicy)
        self.digital_lcd3.setSmallDecimalPoint(False)
        self.digital_lcd3.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.digital_lcd3.setObjectName("digital_lcd3")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.digital_lcd3)
        self.digital_chk4 = QtGui.QCheckBox(self.group_digital)
        self.digital_chk4.setObjectName("digital_chk4")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.digital_chk4)
        self.digital_lcd4 = QtGui.QLCDNumber(self.group_digital)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.digital_lcd4.sizePolicy().hasHeightForWidth())
        self.digital_lcd4.setSizePolicy(sizePolicy)
        self.digital_lcd4.setSmallDecimalPoint(False)
        self.digital_lcd4.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.digital_lcd4.setObjectName("digital_lcd4")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.digital_lcd4)
        self.verticalLayout.addWidget(self.group_digital)
        self.group_speed = QtGui.QGroupBox(LCDGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_speed.sizePolicy().hasHeightForWidth())
        self.group_speed.setSizePolicy(sizePolicy)
        self.group_speed.setTitle("")
        self.group_speed.setObjectName("group_speed")
        self.formLayout_3 = QtGui.QFormLayout(self.group_speed)
        self.formLayout_3.setContentsMargins(2, 2, 2, 2)
        self.formLayout_3.setHorizontalSpacing(2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.speed_chk = QtGui.QCheckBox(self.group_speed)
        self.speed_chk.setObjectName("speed_chk")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.speed_chk)
        self.speed_lcd = QtGui.QLCDNumber(self.group_speed)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speed_lcd.sizePolicy().hasHeightForWidth())
        self.speed_lcd.setSizePolicy(sizePolicy)
        self.speed_lcd.setSmallDecimalPoint(False)
        self.speed_lcd.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.speed_lcd.setObjectName("speed_lcd")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.speed_lcd)
        self.acceleration_chk = QtGui.QCheckBox(self.group_speed)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acceleration_chk.sizePolicy().hasHeightForWidth())
        self.acceleration_chk.setSizePolicy(sizePolicy)
        self.acceleration_chk.setObjectName("acceleration_chk")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.acceleration_chk)
        self.acceleration_lcd = QtGui.QLCDNumber(self.group_speed)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acceleration_lcd.sizePolicy().hasHeightForWidth())
        self.acceleration_lcd.setSizePolicy(sizePolicy)
        self.acceleration_lcd.setSmallDecimalPoint(False)
        self.acceleration_lcd.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.acceleration_lcd.setObjectName("acceleration_lcd")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.acceleration_lcd)
        self.shift_chk = QtGui.QCheckBox(self.group_speed)
        self.shift_chk.setObjectName("shift_chk")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.shift_chk)
        self.shift_lcd = QtGui.QLCDNumber(self.group_speed)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shift_lcd.sizePolicy().hasHeightForWidth())
        self.shift_lcd.setSizePolicy(sizePolicy)
        self.shift_lcd.setSmallDecimalPoint(False)
        self.shift_lcd.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.shift_lcd.setObjectName("shift_lcd")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.shift_lcd)
        self.verticalLayout.addWidget(self.group_speed)

        self.retranslateUi(LCDGroup)
        QtCore.QMetaObject.connectSlotsByName(LCDGroup)

    def retranslateUi(self, LCDGroup):
        LCDGroup.setWindowTitle(QtGui.QApplication.translate("LCDGroup", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.st_transfer.setText(QtGui.QApplication.translate("LCDGroup", "S-T", None, QtGui.QApplication.UnicodeUTF8))
        self.group_press.setTitle(QtGui.QApplication.translate("LCDGroup", "压力", None, QtGui.QApplication.UnicodeUTF8))
        self.press_chk1.setText(QtGui.QApplication.translate("LCDGroup", "通道1", None, QtGui.QApplication.UnicodeUTF8))
        self.press_chk2.setText(QtGui.QApplication.translate("LCDGroup", "通道2", None, QtGui.QApplication.UnicodeUTF8))
        self.press_chk3.setText(QtGui.QApplication.translate("LCDGroup", "通道3", None, QtGui.QApplication.UnicodeUTF8))
        self.press_chk4.setText(QtGui.QApplication.translate("LCDGroup", "通道4", None, QtGui.QApplication.UnicodeUTF8))
        self.press_chk5.setText(QtGui.QApplication.translate("LCDGroup", "通道5", None, QtGui.QApplication.UnicodeUTF8))
        self.press_chk6.setText(QtGui.QApplication.translate("LCDGroup", "通道6", None, QtGui.QApplication.UnicodeUTF8))
        self.group_digital.setTitle(QtGui.QApplication.translate("LCDGroup", "数字量/计时", None, QtGui.QApplication.UnicodeUTF8))
        self.digital_chk1.setText(QtGui.QApplication.translate("LCDGroup", "通道1", None, QtGui.QApplication.UnicodeUTF8))
        self.digital_chk2.setText(QtGui.QApplication.translate("LCDGroup", "通道2", None, QtGui.QApplication.UnicodeUTF8))
        self.digital_chk3.setText(QtGui.QApplication.translate("LCDGroup", "通道3", None, QtGui.QApplication.UnicodeUTF8))
        self.digital_chk4.setText(QtGui.QApplication.translate("LCDGroup", "通道4", None, QtGui.QApplication.UnicodeUTF8))
        self.speed_chk.setText(QtGui.QApplication.translate("LCDGroup", "速度", None, QtGui.QApplication.UnicodeUTF8))
        self.acceleration_chk.setText(QtGui.QApplication.translate("LCDGroup", "加速度", None, QtGui.QApplication.UnicodeUTF8))
        self.shift_chk.setText(QtGui.QApplication.translate("LCDGroup", "位移", None, QtGui.QApplication.UnicodeUTF8))

import Icons_rc
