# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_designer\MainWindow.ui'
#
# Created: Tue Oct 29 11:06:03 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 640)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(960, 640))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QToolBar{\n"
"font-family:\"Arial\";\n"
"}\n"
"QLabel{\n"
"font-family:\"Arial\";\n"
"}\n"
"QPushButton{\n"
"font-family:\"Arial\";\n"
"}\n"
"QAction{\n"
"font-family:\"Arial\";\n"
"}")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_container = QtGui.QWidget(self.centralwidget)
        self.widget_container.setObjectName("widget_container")
        self.horizontalLayout.addWidget(self.widget_container)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.frame_container = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_container.sizePolicy().hasHeightForWidth())
        self.frame_container.setSizePolicy(sizePolicy)
        self.frame_container.setMinimumSize(QtCore.QSize(160, 0))
        self.frame_container.setMaximumSize(QtCore.QSize(160, 16777215))
        self.frame_container.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_container.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_container.setObjectName("frame_container")
        self.horizontalLayout.addWidget(self.frame_container)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setCursor(QtCore.Qt.PointingHandCursor)
        self.toolBar.setAllowedAreas(QtCore.Qt.NoToolBarArea)
        self.toolBar.setIconSize(QtCore.QSize(80, 60))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_config = QtGui.QAction(MainWindow)
        self.action_config.setChecked(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/toolbar/config2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_config.setIcon(icon1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.action_config.setFont(font)
        self.action_config.setAutoRepeat(True)
        self.action_config.setVisible(True)
        self.action_config.setPriority(QtGui.QAction.NormalPriority)
        self.action_config.setObjectName("action_config")
        self.action_start = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/toolbar/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_start.setIcon(icon2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.action_start.setFont(font)
        self.action_start.setObjectName("action_start")
        self.action_reset = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/toolbar/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_reset.setIcon(icon3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.action_reset.setFont(font)
        self.action_reset.setObjectName("action_reset")
        self.action_result = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/toolbar/display.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_result.setIcon(icon4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.action_result.setFont(font)
        self.action_result.setObjectName("action_result")
        self.action_print = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/toolbar/printer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_print.setIcon(icon5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.action_print.setFont(font)
        self.action_print.setObjectName("action_print")
        self.action_back = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/toolbar/disconnect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_back.setIcon(icon6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.action_back.setFont(font)
        self.action_back.setObjectName("action_back")
        self.action_exit = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/toolbar/door.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_exit.setIcon(icon7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.action_exit.setFont(font)
        self.action_exit.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.action_exit.setObjectName("action_exit")
        self.action_read_report = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/toolbar/readfiles.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_read_report.setIcon(icon8)
        self.action_read_report.setObjectName("action_read_report")
        self.toolBar.addAction(self.action_config)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_start)
        self.toolBar.addAction(self.action_reset)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_result)
        self.toolBar.addAction(self.action_print)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_read_report)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_back)
        self.toolBar.addAction(self.action_exit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "AYR-641A型发射参数测试仪", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.action_config.setText(QtGui.QApplication.translate("MainWindow", "参数设置", None, QtGui.QApplication.UnicodeUTF8))
        self.action_config.setToolTip(QtGui.QApplication.translate("MainWindow", "参数设置", None, QtGui.QApplication.UnicodeUTF8))
        self.action_config.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.action_start.setText(QtGui.QApplication.translate("MainWindow", "开始", None, QtGui.QApplication.UnicodeUTF8))
        self.action_start.setToolTip(QtGui.QApplication.translate("MainWindow", "开始测量", None, QtGui.QApplication.UnicodeUTF8))
        self.action_start.setShortcut(QtGui.QApplication.translate("MainWindow", "F2", None, QtGui.QApplication.UnicodeUTF8))
        self.action_reset.setText(QtGui.QApplication.translate("MainWindow", "复位", None, QtGui.QApplication.UnicodeUTF8))
        self.action_reset.setToolTip(QtGui.QApplication.translate("MainWindow", "复位", None, QtGui.QApplication.UnicodeUTF8))
        self.action_reset.setShortcut(QtGui.QApplication.translate("MainWindow", "F3", None, QtGui.QApplication.UnicodeUTF8))
        self.action_result.setText(QtGui.QApplication.translate("MainWindow", "显示结果", None, QtGui.QApplication.UnicodeUTF8))
        self.action_result.setToolTip(QtGui.QApplication.translate("MainWindow", "显示结果", None, QtGui.QApplication.UnicodeUTF8))
        self.action_result.setShortcut(QtGui.QApplication.translate("MainWindow", "F4", None, QtGui.QApplication.UnicodeUTF8))
        self.action_print.setText(QtGui.QApplication.translate("MainWindow", "打印报告", None, QtGui.QApplication.UnicodeUTF8))
        self.action_print.setToolTip(QtGui.QApplication.translate("MainWindow", "打印报告", None, QtGui.QApplication.UnicodeUTF8))
        self.action_print.setShortcut(QtGui.QApplication.translate("MainWindow", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.action_back.setText(QtGui.QApplication.translate("MainWindow", "首页/断开", None, QtGui.QApplication.UnicodeUTF8))
        self.action_back.setToolTip(QtGui.QApplication.translate("MainWindow", "首页/断开", None, QtGui.QApplication.UnicodeUTF8))
        self.action_back.setShortcut(QtGui.QApplication.translate("MainWindow", "F7", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit.setText(QtGui.QApplication.translate("MainWindow", "退出", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit.setToolTip(QtGui.QApplication.translate("MainWindow", "退出软件", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit.setShortcut(QtGui.QApplication.translate("MainWindow", "F8", None, QtGui.QApplication.UnicodeUTF8))
        self.action_read_report.setText(QtGui.QApplication.translate("MainWindow", "读取报告", None, QtGui.QApplication.UnicodeUTF8))
        self.action_read_report.setToolTip(QtGui.QApplication.translate("MainWindow", "读取报告", None, QtGui.QApplication.UnicodeUTF8))
        self.action_read_report.setShortcut(QtGui.QApplication.translate("MainWindow", "F6", None, QtGui.QApplication.UnicodeUTF8))

import Icons_rc
import Lang_rc
