# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_designer\ReportDialog.ui'
#
# Created: Mon Dec 09 09:45:18 2013
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ReportDialog(object):
    def setupUi(self, ReportDialog):
        ReportDialog.setObjectName("ReportDialog")
        ReportDialog.resize(500, 300)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ReportDialog.sizePolicy().hasHeightForWidth())
        ReportDialog.setSizePolicy(sizePolicy)
        ReportDialog.setMinimumSize(QtCore.QSize(500, 300))
        ReportDialog.setMaximumSize(QtCore.QSize(500, 300))
        self.horizontalLayout = QtGui.QHBoxLayout(ReportDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.press_name6 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.press_name6.setFont(font)
        self.press_name6.setObjectName("press_name6")
        self.gridLayout.addWidget(self.press_name6, 5, 0, 1, 1)
        self.press_ch6 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.press_ch6.setFont(font)
        self.press_ch6.setStyleSheet("background:#ffffff")
        self.press_ch6.setAlignment(QtCore.Qt.AlignCenter)
        self.press_ch6.setObjectName("press_ch6")
        self.gridLayout.addWidget(self.press_ch6, 5, 1, 1, 1)
        self.press_ch2 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.press_ch2.setFont(font)
        self.press_ch2.setStyleSheet("background:#ffffff")
        self.press_ch2.setAlignment(QtCore.Qt.AlignCenter)
        self.press_ch2.setObjectName("press_ch2")
        self.gridLayout.addWidget(self.press_ch2, 1, 1, 1, 1)
        self.press_ch4 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.press_ch4.setFont(font)
        self.press_ch4.setStyleSheet("background:#ffffff")
        self.press_ch4.setAlignment(QtCore.Qt.AlignCenter)
        self.press_ch4.setObjectName("press_ch4")
        self.gridLayout.addWidget(self.press_ch4, 3, 1, 1, 1)
        self.press_name3 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.press_name3.setFont(font)
        self.press_name3.setObjectName("press_name3")
        self.gridLayout.addWidget(self.press_name3, 2, 0, 1, 1)
        self.press_ch3 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.press_ch3.setFont(font)
        self.press_ch3.setStyleSheet("background:#ffffff")
        self.press_ch3.setAlignment(QtCore.Qt.AlignCenter)
        self.press_ch3.setObjectName("press_ch3")
        self.gridLayout.addWidget(self.press_ch3, 2, 1, 1, 1)
        self.press_ch5 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.press_ch5.setFont(font)
        self.press_ch5.setStyleSheet("background:#ffffff")
        self.press_ch5.setAlignment(QtCore.Qt.AlignCenter)
        self.press_ch5.setObjectName("press_ch5")
        self.gridLayout.addWidget(self.press_ch5, 4, 1, 1, 1)
        self.press_name2 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.press_name2.setFont(font)
        self.press_name2.setObjectName("press_name2")
        self.gridLayout.addWidget(self.press_name2, 1, 0, 1, 1)
        self.press_name5 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.press_name5.setFont(font)
        self.press_name5.setObjectName("press_name5")
        self.gridLayout.addWidget(self.press_name5, 4, 0, 1, 1)
        self.press_ch1 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.press_ch1.setFont(font)
        self.press_ch1.setStyleSheet("background:#ffffff")
        self.press_ch1.setTextFormat(QtCore.Qt.AutoText)
        self.press_ch1.setAlignment(QtCore.Qt.AlignCenter)
        self.press_ch1.setObjectName("press_ch1")
        self.gridLayout.addWidget(self.press_ch1, 0, 1, 1, 1)
        self.press_name4 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.press_name4.setFont(font)
        self.press_name4.setObjectName("press_name4")
        self.gridLayout.addWidget(self.press_name4, 3, 0, 1, 1)
        self.press_name1 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.press_name1.setFont(font)
        self.press_name1.setFrameShape(QtGui.QFrame.NoFrame)
        self.press_name1.setFrameShadow(QtGui.QFrame.Sunken)
        self.press_name1.setObjectName("press_name1")
        self.gridLayout.addWidget(self.press_name1, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.line = QtGui.QFrame(ReportDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.shoot_deep = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.shoot_deep.setFont(font)
        self.shoot_deep.setStyleSheet("background:#ffffff")
        self.shoot_deep.setAlignment(QtCore.Qt.AlignCenter)
        self.shoot_deep.setWordWrap(False)
        self.shoot_deep.setObjectName("shoot_deep")
        self.gridLayout_4.addWidget(self.shoot_deep, 2, 1, 1, 2)
        self.label_41 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.gridLayout_4.addWidget(self.label_41, 2, 0, 1, 1)
        self.speed = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.speed.setFont(font)
        self.speed.setStyleSheet("background:#ffffff")
        self.speed.setAlignment(QtCore.Qt.AlignCenter)
        self.speed.setObjectName("speed")
        self.gridLayout_4.addWidget(self.speed, 0, 1, 1, 2)
        self.label_11 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 1)
        self.acceleration = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.acceleration.setFont(font)
        self.acceleration.setStyleSheet("background:#ffffff")
        self.acceleration.setAlignment(QtCore.Qt.AlignCenter)
        self.acceleration.setObjectName("acceleration")
        self.gridLayout_4.addWidget(self.acceleration, 1, 1, 1, 2)
        self.label_12 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.line_2 = QtGui.QFrame(ReportDialog)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bleed_time = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bleed_time.setFont(font)
        self.bleed_time.setStyleSheet("background:#ffffff")
        self.bleed_time.setAlignment(QtCore.Qt.AlignCenter)
        self.bleed_time.setObjectName("bleed_time")
        self.gridLayout_2.addWidget(self.bleed_time, 5, 1, 1, 1)
        self.label_43 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.gridLayout_2.addWidget(self.label_43, 5, 0, 1, 1)
        self.bleed_open_time = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bleed_open_time.setFont(font)
        self.bleed_open_time.setStyleSheet("background:#ffffff")
        self.bleed_open_time.setAlignment(QtCore.Qt.AlignCenter)
        self.bleed_open_time.setObjectName("bleed_open_time")
        self.gridLayout_2.addWidget(self.bleed_open_time, 4, 1, 1, 1)
        self.label_42 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.gridLayout_2.addWidget(self.label_42, 4, 0, 1, 1)
        self.label_39 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.gridLayout_2.addWidget(self.label_39, 3, 0, 1, 1)
        self.label_40 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.gridLayout_2.addWidget(self.label_40, 0, 0, 1, 1)
        self.test_program = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.test_program.setFont(font)
        self.test_program.setStyleSheet("background:#ffffff")
        self.test_program.setAlignment(QtCore.Qt.AlignCenter)
        self.test_program.setObjectName("test_program")
        self.gridLayout_2.addWidget(self.test_program, 0, 1, 1, 1)
        self.label_37 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.gridLayout_2.addWidget(self.label_37, 1, 0, 1, 1)
        self.trigger_method = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.trigger_method.setFont(font)
        self.trigger_method.setStyleSheet("background:#ffffff")
        self.trigger_method.setAlignment(QtCore.Qt.AlignCenter)
        self.trigger_method.setObjectName("trigger_method")
        self.gridLayout_2.addWidget(self.trigger_method, 1, 1, 1, 1)
        self.delay_time = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delay_time.setFont(font)
        self.delay_time.setStyleSheet("background:#ffffff")
        self.delay_time.setAlignment(QtCore.Qt.AlignCenter)
        self.delay_time.setObjectName("delay_time")
        self.gridLayout_2.addWidget(self.delay_time, 2, 1, 1, 1)
        self.label_38 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.gridLayout_2.addWidget(self.label_38, 2, 0, 1, 1)
        self.shoot_time = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.shoot_time.setFont(font)
        self.shoot_time.setStyleSheet("background:#ffffff")
        self.shoot_time.setAlignment(QtCore.Qt.AlignCenter)
        self.shoot_time.setObjectName("shoot_time")
        self.gridLayout_2.addWidget(self.shoot_time, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line_3 = QtGui.QFrame(ReportDialog)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.digital_name2 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.digital_name2.setFont(font)
        self.digital_name2.setObjectName("digital_name2")
        self.gridLayout_3.addWidget(self.digital_name2, 2, 0, 1, 1)
        self.digital_open_ch2 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.digital_open_ch2.setFont(font)
        self.digital_open_ch2.setStyleSheet("background:#ffffff")
        self.digital_open_ch2.setAlignment(QtCore.Qt.AlignCenter)
        self.digital_open_ch2.setObjectName("digital_open_ch2")
        self.gridLayout_3.addWidget(self.digital_open_ch2, 2, 1, 1, 1)
        self.digital_name4 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.digital_name4.setFont(font)
        self.digital_name4.setObjectName("digital_name4")
        self.gridLayout_3.addWidget(self.digital_name4, 4, 0, 1, 1)
        self.digital_open_ch4 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.digital_open_ch4.setFont(font)
        self.digital_open_ch4.setStyleSheet("background:#ffffff")
        self.digital_open_ch4.setAlignment(QtCore.Qt.AlignCenter)
        self.digital_open_ch4.setObjectName("digital_open_ch4")
        self.gridLayout_3.addWidget(self.digital_open_ch4, 4, 1, 1, 1)
        self.digital_open_ch3 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.digital_open_ch3.setFont(font)
        self.digital_open_ch3.setStyleSheet("background:#ffffff")
        self.digital_open_ch3.setAlignment(QtCore.Qt.AlignCenter)
        self.digital_open_ch3.setObjectName("digital_open_ch3")
        self.gridLayout_3.addWidget(self.digital_open_ch3, 3, 1, 1, 1)
        self.digital_name3 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.digital_name3.setFont(font)
        self.digital_name3.setObjectName("digital_name3")
        self.gridLayout_3.addWidget(self.digital_name3, 3, 0, 1, 1)
        self.label_51 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.gridLayout_3.addWidget(self.label_51, 0, 0, 1, 1)
        self.label_52 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.gridLayout_3.addWidget(self.label_52, 0, 1, 1, 1)
        self.digital_name1 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.digital_name1.setFont(font)
        self.digital_name1.setObjectName("digital_name1")
        self.gridLayout_3.addWidget(self.digital_name1, 1, 0, 1, 1)
        self.digital_open_ch1 = QtGui.QLabel(ReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.digital_open_ch1.setFont(font)
        self.digital_open_ch1.setStyleSheet("background:#ffffff")
        self.digital_open_ch1.setAlignment(QtCore.Qt.AlignCenter)
        self.digital_open_ch1.setObjectName("digital_open_ch1")
        self.gridLayout_3.addWidget(self.digital_open_ch1, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(ReportDialog)
        QtCore.QMetaObject.connectSlotsByName(ReportDialog)

    def retranslateUi(self, ReportDialog):
        ReportDialog.setWindowTitle(QtGui.QApplication.translate("ReportDialog", "测试结果", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ReportDialog", "压力（MPa）", None, QtGui.QApplication.UnicodeUTF8))
        self.press_name6.setText(QtGui.QApplication.translate("ReportDialog", "通道6", None, QtGui.QApplication.UnicodeUTF8))
        self.press_ch6.setText(QtGui.QApplication.translate("ReportDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.press_ch2.setText(QtGui.QApplication.translate("ReportDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.press_ch4.setText(QtGui.QApplication.translate("ReportDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.press_name3.setText(QtGui.QApplication.translate("ReportDialog", "通道3", None, QtGui.QApplication.UnicodeUTF8))
        self.press_ch3.setText(QtGui.QApplication.translate("ReportDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.press_ch5.setText(QtGui.QApplication.translate("ReportDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.press_name2.setText(QtGui.QApplication.translate("ReportDialog", "通道2", None, QtGui.QApplication.UnicodeUTF8))
        self.press_name5.setText(QtGui.QApplication.translate("ReportDialog", "通道5", None, QtGui.QApplication.UnicodeUTF8))
        self.press_ch1.setText(QtGui.QApplication.translate("ReportDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.press_name4.setText(QtGui.QApplication.translate("ReportDialog", "通道4", None, QtGui.QApplication.UnicodeUTF8))
        self.press_name1.setText(QtGui.QApplication.translate("ReportDialog", "通道1", None, QtGui.QApplication.UnicodeUTF8))
        self.shoot_deep.setText(QtGui.QApplication.translate("ReportDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("ReportDialog", "发射深度(m)", None, QtGui.QApplication.UnicodeUTF8))
        self.speed.setText(QtGui.QApplication.translate("ReportDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("ReportDialog", "出管速度(m/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.acceleration.setText(QtGui.QApplication.translate("ReportDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("ReportDialog", "加速度(g)", None, QtGui.QApplication.UnicodeUTF8))
        self.bleed_time.setText(QtGui.QApplication.translate("ReportDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("ReportDialog", "泄放阀开启时机(m)", None, QtGui.QApplication.UnicodeUTF8))
        self.bleed_open_time.setText(QtGui.QApplication.translate("ReportDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("ReportDialog", "泄放阀开启时间(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("ReportDialog", "发射时间(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("ReportDialog", "测试类型", None, QtGui.QApplication.UnicodeUTF8))
        self.test_program.setText(QtGui.QApplication.translate("ReportDialog", "鱼雷", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("ReportDialog", "触发方式", None, QtGui.QApplication.UnicodeUTF8))
        self.trigger_method.setText(QtGui.QApplication.translate("ReportDialog", "手动触发", None, QtGui.QApplication.UnicodeUTF8))
        self.delay_time.setText(QtGui.QApplication.translate("ReportDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("ReportDialog", "延迟时间(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.shoot_time.setText(QtGui.QApplication.translate("ReportDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.digital_name2.setText(QtGui.QApplication.translate("ReportDialog", "通道2", None, QtGui.QApplication.UnicodeUTF8))
        self.digital_open_ch2.setText(QtGui.QApplication.translate("ReportDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.digital_name4.setText(QtGui.QApplication.translate("ReportDialog", "通道4", None, QtGui.QApplication.UnicodeUTF8))
        self.digital_open_ch4.setText(QtGui.QApplication.translate("ReportDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.digital_open_ch3.setText(QtGui.QApplication.translate("ReportDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.digital_name3.setText(QtGui.QApplication.translate("ReportDialog", "通道3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("ReportDialog", "数字量(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("ReportDialog", "开启时间", None, QtGui.QApplication.UnicodeUTF8))
        self.digital_name1.setText(QtGui.QApplication.translate("ReportDialog", "通道1", None, QtGui.QApplication.UnicodeUTF8))
        self.digital_open_ch1.setText(QtGui.QApplication.translate("ReportDialog", "0", None, QtGui.QApplication.UnicodeUTF8))

import Icons_rc
